[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --access-logfile - --error-logfile - --log-level info"
healthcheckPath = "/ping"
healthcheckTimeout = 60
healthcheckInterval = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { COMPRESS_LEVEL = "9", CACHE_TYPE = "simple", CACHE_DEFAULT_TIMEOUT = "600" }
